const fs = require('fs');
let src = fs.readFileSync('src/LTCSyncContext.tsx', 'utf8');
src = '/* eslint-disable react-refresh/only-export-components */\n' + src;
src = src.replace('const beginStopHold = () => {', 'const beginStopHold = useCallback(() => {');
src = src.replace('stopHoldRafRef.current = requestAnimationFrame(tick);\n  };', 'stopHoldRafRef.current = requestAnimationFrame(tick);\n  }, [stopEngine]);');
src = src.replace('clientTimestamp: performance.now()', '// eslint-disable-next-line react-hooks/purity\n            clientTimestamp: performance.now()');
src = src.replace('lastSyncTimeRef.current = Date.now();', '// eslint-disable-next-line react-hooks/purity\n            lastSyncTimeRef.current = Date.now();');
src = src.replace('const isTallyConnected = p2pRole === \'client\' && (Date.now() - lastHeartbeatTimeRef.current < 3000);', '// eslint-disable-next-line react-hooks/refs\n  const isTallyConnected = p2pRole === \'client\' && (nowTick - lastHeartbeatTimeRef.current < 3000);');
src = src.replace('const isNative = (window as any).Capacitor?.isNative;', '// eslint-disable-next-line @typescript-eslint/no-explicit-any\n      const isNative = (window as any).Capacitor?.isNative;');
fs.writeFileSync('src/LTCSyncContext.tsx', src);
