import { Peer } from 'peerjs';
import type { DataConnection } from 'peerjs';

import type { TallyPayload } from './tally';
import { debug } from './log';

export interface SyncMessage {
  type: 'sync-request' | 'sync-response' | 'heartbeat' | 'report' | 'tally' | 'webrtc-offer' | 'webrtc-answer' | 'webrtc-candidate';
  masterTimecode: string;
  masterTimestamp: number;
  fps: number;
  isDropFrame: boolean;
  isRunning: boolean;
  isPaused?: boolean;
  clientTimestamp?: number;
  clientId?: string; // Identifier for the sender
  targetId?: string; // Identifier for the intended recipient (used for signaling)
  rtt?: number;      // Reported RTT from client
  drift?: number;    // Reported drift from client
  tally?: TallyPayload;
  sdp?: RTCSessionDescriptionInit; // For WebRTC signaling
  candidate?: RTCIceCandidateInit; // For WebRTC signaling
}

/** Factory used to create the underlying Peer — overridable for tests. */
export type PeerFactory = (id: string, options: object) => Peer;

/** Fixed length of the short peer id generated by generateShortId(). */
export const PEER_ID_LENGTH = 4;

/** DataConnection label used for the dedicated, reliable WebRTC-signaling channel. */
const SIGNALING_LABEL = 'webrtc-signal';

export class PeerSync {
  private peer: Peer | null = null;
  private connections: DataConnection[] = [];
  // Signaling (offer/answer/ICE candidate) needs guaranteed, ordered delivery,
  // unlike the lossy-tolerant `connections` above (deliberately `reliable:
  // false` for low-latency timecode sync). Kept as a separate labeled,
  // `reliable: true` DataConnection per peer so a dropped signaling message
  // can't silently break the WebRTC handshake.
  private signalingConnections = new Map<string, DataConnection>();
  private pendingSignalingSends = new Map<string, SyncMessage[]>();
  private onMessageCallback: (msg: SyncMessage) => void;
  private onSignalingCallback?: (msg: SyncMessage) => void;
  private onStatusCallback: (status: string) => void;
  private lossRate: number = 0;
  private peerFactory: PeerFactory;

  constructor(
    onMessage: (msg: SyncMessage) => void,
    onStatus: (status: string) => void,
    peerFactory: PeerFactory = (id, options) => new Peer(id, options),
    onSignaling?: (msg: SyncMessage) => void
  ) {
    this.onMessageCallback = onMessage;
    this.onStatusCallback = onStatus;
    this.peerFactory = peerFactory;
    this.onSignalingCallback = onSignaling;
  }

  private generateShortId(): string {
    const chars = '0123456789ABCDEFGHJKLMNPQRSTUVWXYZ'; // Confusion-prone I, O removed
    let result = '';
    for (let i = 0; i < PEER_ID_LENGTH; i++) {
      result += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    return result;
  }

  public initialize(): Promise<string> {
    return new Promise((resolve, reject) => {
      try {
        const shortId = this.generateShortId();
        // Use injected factory (defaults to real Peer) with ICE servers for NAT traversal
        this.peer = this.peerFactory(shortId, {
          debug: 2,
          config: {
            'iceServers': [
              { 'urls': 'stun:stun.l.google.com:19302' },
              { 'urls': 'stun:stun1.l.google.com:19302' },
              { 'urls': 'stun:stun2.l.google.com:19302' },
              { 'urls': 'stun:stun3.l.google.com:19302' },
              { 'urls': 'stun:stun4.l.google.com:19302' },
            ]
          }
        });

        this.peer.on('open', (id: string) => {
          this.onStatusCallback(`READY: ID ${id}`);
          resolve(id);
        });

        this.peer.on('connection', (conn: DataConnection) => {
          this.onStatusCallback(`CONNECTED TO CLIENT: ${conn.peer}`);
          this.handleConnection(conn);
        });

        this.peer.on('error', (err) => {
          console.error('Peer error:', err);
          this.onStatusCallback(`ERROR: ${err.type}`);
          reject(err);
        });
      } catch (err) {
        console.error('Failed to initialize PeerJS:', err);
        this.onStatusCallback('ERROR: PeerJS NOT LOADED');
        reject(err instanceof Error ? err : new Error(String(err)));
      }
    });
  }

  public connect(peerId: string) {
    if (!this.peer) return;
    const conn = this.peer.connect(peerId, {
      reliable: false // Use unreliable (UDP-style) for low latency TC
    });
    this.onStatusCallback(`CONNECTING TO ${peerId}...`);
    this.handleConnection(conn);
  }

  private handleConnection(conn: DataConnection) {
    const isSignaling = conn.label === SIGNALING_LABEL;

    if (isSignaling) {
      this.signalingConnections.set(conn.peer, conn);
    } else {
      this.connections.push(conn);
    }

    conn.on('open', () => {
      this.onStatusCallback(`CONNECTED TO ${conn.peer}`);
      debug('Connection opened with:', conn.peer);
      if (isSignaling) {
        this.flushPendingSignaling(conn.peer, conn);
      }
    });

    conn.on('data', (data: unknown) => {
      const msg = data as SyncMessage;
      msg.clientId = conn.peer; // Identify the sender

      if (isSignaling || msg.type.startsWith('webrtc-')) {
        if (this.onSignalingCallback) {
          this.onSignalingCallback(msg);
        }
        return;
      }

      // Master logic: Answer to sync-request automatically
      if (msg.type === 'sync-request' && this.onMessageCallback) {
        this.onMessageCallback({ ...msg, clientTimestamp: msg.clientTimestamp });
      } else {
        this.onMessageCallback(msg);
      }
    });

    conn.on('close', () => {
      this.onStatusCallback('CONNECTION CLOSED');
      if (isSignaling) {
        this.discardSignalingConnection(conn);
      } else {
        this.connections = this.connections.filter(c => c !== conn);
      }
    });

    if (isSignaling) {
      // A signaling connection that never opens (peer unreachable, etc.) may
      // emit 'error' instead of 'close' — without this, its stale queue would
      // never be cleared and would get flushed alongside a later, unrelated
      // connection attempt to the same target.
      conn.on('error', () => {
        this.discardSignalingConnection(conn);
      });
    }
  }

  /** Drops a signaling connection and any messages still queued for it. */
  private discardSignalingConnection(conn: DataConnection): void {
    if (this.signalingConnections.get(conn.peer) === conn) {
      this.signalingConnections.delete(conn.peer);
    }
    this.pendingSignalingSends.delete(conn.peer);
  }

  /** Lazily creates (or reuses) the reliable signaling DataConnection to targetId. */
  private getOrCreateSignalingConnection(targetId: string): DataConnection | null {
    const existing = this.signalingConnections.get(targetId);
    if (existing) return existing;
    if (!this.peer) return null;

    const conn = this.peer.connect(targetId, {
      label: SIGNALING_LABEL,
      reliable: true,
    });
    this.handleConnection(conn);
    return conn;
  }

  /** Flushes signaling messages queued while the connection to targetId was still opening. */
  private flushPendingSignaling(targetId: string, conn: DataConnection): void {
    const queued = this.pendingSignalingSends.get(targetId);
    if (!queued) return;
    this.pendingSignalingSends.delete(targetId);
    queued.forEach(m => void conn.send(m));
  }

  /**
   * Sends a WebRTC signaling message over the dedicated reliable channel,
   * bypassing the simulated loss-rate gate entirely — a dropped offer/answer/
   * ICE candidate breaks the handshake outright, unlike lossy sync traffic
   * which tolerates the occasional drop.
   */
  private sendSignaling(targetId: string, msg: SyncMessage): void {
    const conn = this.getOrCreateSignalingConnection(targetId);
    if (!conn) return;
    if (conn.open) {
      void conn.send(msg);
    } else {
      const queue = this.pendingSignalingSends.get(targetId) ?? [];
      queue.push(msg);
      this.pendingSignalingSends.set(targetId, queue);
    }
  }

  public setLossRate(rate: number): void {
    this.lossRate = Math.max(0, Math.min(1, rate));
  }

  /** Current simulated packet-loss rate in [0, 1]. */
  public getLossRate(): number {
    return this.lossRate;
  }

  public send(msg: SyncMessage) {
    this.connections.forEach(conn => {
      if (conn.open && Math.random() >= this.lossRate) {
        void conn.send(msg);
      }
    });
  }

  public sendTo(targetId: string, msg: SyncMessage) {
    msg.targetId = targetId;

    if (msg.type.startsWith('webrtc-')) {
      this.sendSignaling(targetId, msg);
      return;
    }

    const conn = this.connections.find(c => c.peer === targetId);
    if (conn && conn.open && Math.random() >= this.lossRate) {
      void conn.send(msg);
    }
  }

  public broadcast(msg: SyncMessage) {
    this.send(msg);
  }

  public destroy() {
    this.signalingConnections.forEach(conn => conn.close());
    this.signalingConnections.clear();
    this.pendingSignalingSends.clear();
    this.peer?.destroy();
  }
}
