import { Peer } from 'peerjs';
import type { DataConnection } from 'peerjs';

import type { TallyPayload } from './tally';
import { debug } from './log';
import { ICE_SERVERS } from './iceServers';
import { computeBackoffDelay } from './backoff';

export interface SyncMessage {
  type: 'sync-request' | 'sync-response' | 'heartbeat' | 'report' | 'tally' | 'webrtc-offer' | 'webrtc-answer' | 'webrtc-candidate' | 'set-bitrate';
  masterTimecode: string;
  masterTimestamp: number;
  fps: number;
  isDropFrame: boolean;
  isRunning: boolean;
  isPaused?: boolean;
  clientTimestamp?: number;
  clientId?: string; // Identifier for the sender
  targetId?: string; // Identifier for the intended recipient (used for signaling)
  rtt?: number;      // Reported RTT from client
  drift?: number;    // Reported drift from client
  tally?: TallyPayload;
  sdp?: RTCSessionDescriptionInit; // For WebRTC signaling
  candidate?: RTCIceCandidateInit; // For WebRTC signaling
  bitrateBps?: number;             // Dynamic bandwidth limit config
}

/** Factory used to create the underlying Peer — overridable for tests. */
export type PeerFactory = (id: string, options: object) => Peer;

/** Fixed length of the short peer id generated by generateShortId(). */
export const PEER_ID_LENGTH = 4;

/**
 * How many times a fresh short id is generated when the signaling server
 * reports the drawn one is already taken. The 4-character id is deliberately
 * short so it can be read aloud and typed on set, which means collisions are
 * possible (32^4 ≈ 1.05M combinations); redrawing on 'unavailable-id' keeps
 * that a non-event for the operator instead of a dead session that has to be
 * reset by hand.
 */
export const PEER_ID_RETRY_LIMIT = 5;

/**
 * How many times the PeerJS signaling socket is re-dialled after it drops.
 * With the default backoff curve this spans roughly three minutes — long
 * enough to ride out a tunnel or a lift, short enough to stop eventually.
 */
export const SIGNALING_RECONNECT_LIMIT = 8;

/** DataConnection label used for the dedicated, reliable WebRTC-signaling channel. */
const SIGNALING_LABEL = 'webrtc-signal';

export class PeerSync {
  private peer: Peer | null = null;
  private connections: DataConnection[] = [];
  // Signaling (offer/answer/ICE candidate) needs guaranteed, ordered delivery,
  // unlike the lossy-tolerant `connections` above (deliberately `reliable:
  // false` for low-latency timecode sync). Kept as a separate labeled,
  // `reliable: true` DataConnection per peer so a dropped signaling message
  // can't silently break the WebRTC handshake.
  private signalingConnections = new Map<string, DataConnection>();
  private pendingSignalingSends = new Map<string, SyncMessage[]>();
  private onMessageCallback: (msg: SyncMessage) => void;
  private onSignalingCallback?: (msg: SyncMessage) => void;
  private onStatusCallback: (status: string) => void;
  private lossRate: number = 0;
  private peerFactory: PeerFactory;
  private reconnectAttempt = 0;
  private reconnectTimer: ReturnType<typeof setTimeout> | null = null;
  private isDestroyed = false;

  constructor(
    onMessage: (msg: SyncMessage) => void,
    onStatus: (status: string) => void,
    peerFactory: PeerFactory = (id, options) => new Peer(id, options),
    onSignaling?: (msg: SyncMessage) => void
  ) {
    this.onMessageCallback = onMessage;
    this.onStatusCallback = onStatus;
    this.peerFactory = peerFactory;
    this.onSignalingCallback = onSignaling;
  }

  private generateShortId(): string {
    const chars = '0123456789ABCDEFGHJKLMNPQRSTUVWXYZ'; // Confusion-prone I, O removed
    let result = '';
    for (let i = 0; i < PEER_ID_LENGTH; i++) {
      result += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    return result;
  }

  public initialize(): Promise<string> {
    this.isDestroyed = false;
    return new Promise((resolve, reject) => {
      this.openPeer(0, resolve, reject);
    });
  }

  /**
   * Creates the underlying Peer with a freshly drawn short id and wires its
   * lifecycle events. Re-entered (with idAttempt + 1) when the signaling
   * server rejects the drawn id as already taken — see PEER_ID_RETRY_LIMIT.
   */
  private openPeer(
    idAttempt: number,
    resolve: (id: string) => void,
    reject: (err: unknown) => void,
  ): void {
    try {
      const shortId = this.generateShortId();
      // Use injected factory (defaults to real Peer) with ICE servers for NAT traversal
      const peer = this.peerFactory(shortId, {
        debug: 2,
        config: {
          'iceServers': ICE_SERVERS,
        }
      });
      this.peer = peer;
      let opened = false;

      peer.on('open', (id: string) => {
        opened = true;
        // Reached on the initial connect and again after every successful
        // signaling reconnect, so this is also where the backoff resets.
        this.clearReconnectTimer();
        this.reconnectAttempt = 0;
        this.onStatusCallback(`READY: ID ${id}`);
        resolve(id);
      });

      peer.on('connection', (conn: DataConnection) => {
        this.onStatusCallback(`CONNECTED TO CLIENT: ${conn.peer}`);
        this.handleConnection(conn);
      });

      // The signaling socket dropped but the Peer object is still usable:
      // existing DataConnections may survive, yet no new peer can find us
      // until it is re-dialled. PeerJS does not retry this on its own.
      peer.on('disconnected', () => {
        if (this.isDestroyed) return;
        this.scheduleSignalingReconnect();
      });

      peer.on('error', (err) => {
        if (!opened && err.type === 'unavailable-id' && idAttempt < PEER_ID_RETRY_LIMIT) {
          debug(`Peer id ${shortId} already taken, redrawing (attempt ${idAttempt + 1})`);
          peer.destroy();
          this.openPeer(idAttempt + 1, resolve, reject);
          return;
        }
        console.error('Peer error:', err);
        this.onStatusCallback(`ERROR: ${err.type}`);
        // After 'open' the promise is already settled; rejecting again would
        // be a no-op, so transient session errors only surface as status.
        if (!opened) reject(err);
      });
    } catch (err) {
      console.error('Failed to initialize PeerJS:', err);
      this.onStatusCallback('ERROR: PeerJS NOT LOADED');
      reject(err instanceof Error ? err : new Error(String(err)));
    }
  }

  /**
   * Re-dials the signaling socket on an exponential backoff. Each attempt
   * re-arms the next one; a successful reconnect emits 'open', which clears
   * the pending timer and resets the attempt counter.
   */
  private scheduleSignalingReconnect(): void {
    if (this.isDestroyed || this.reconnectTimer !== null) return;

    if (this.reconnectAttempt >= SIGNALING_RECONNECT_LIMIT) {
      this.onStatusCallback('ERROR: SIGNALING LOST');
      return;
    }

    const delay = computeBackoffDelay(this.reconnectAttempt);
    this.reconnectAttempt += 1;
    this.onStatusCallback('RECONNECTING...');

    this.reconnectTimer = setTimeout(() => {
      this.reconnectTimer = null;
      const peer = this.peer;
      if (!peer || this.isDestroyed) return;
      if (!peer.disconnected) {
        this.reconnectAttempt = 0;
        return;
      }

      try {
        peer.reconnect();
      } catch (err) {
        debug('Peer reconnect threw', err);
      }
      // Re-arm ahead of the outcome: if the re-dial succeeds, 'open' clears
      // this timer, and if it fails there is no further event to hang the
      // next attempt off.
      this.scheduleSignalingReconnect();
    }, delay);
  }

  private clearReconnectTimer(): void {
    if (this.reconnectTimer !== null) {
      clearTimeout(this.reconnectTimer);
      this.reconnectTimer = null;
    }
  }

  public connect(peerId: string) {
    if (!this.peer) return;
    const conn = this.peer.connect(peerId, {
      reliable: false // Use unreliable (UDP-style) for low latency TC
    });
    this.onStatusCallback(`CONNECTING TO ${peerId}...`);
    this.handleConnection(conn);
  }

  private handleConnection(conn: DataConnection) {
    const isSignaling = conn.label === SIGNALING_LABEL;

    if (isSignaling) {
      this.signalingConnections.set(conn.peer, conn);
    } else {
      this.connections.push(conn);
    }

    conn.on('open', () => {
      this.onStatusCallback(`CONNECTED TO ${conn.peer}`);
      debug('Connection opened with:', conn.peer);
      if (isSignaling) {
        this.flushPendingSignaling(conn.peer, conn);
      }
    });

    conn.on('data', (data: unknown) => {
      const msg = data as SyncMessage;
      msg.clientId = conn.peer; // Identify the sender

      if (isSignaling || msg.type.startsWith('webrtc-')) {
        if (this.onSignalingCallback) {
          this.onSignalingCallback(msg);
        }
        return;
      }

      // Master logic: Answer to sync-request automatically
      if (msg.type === 'sync-request' && this.onMessageCallback) {
        this.onMessageCallback({ ...msg, clientTimestamp: msg.clientTimestamp });
      } else {
        this.onMessageCallback(msg);
      }
    });

    conn.on('close', () => {
      this.onStatusCallback('CONNECTION CLOSED');
      if (isSignaling) {
        this.discardSignalingConnection(conn);
      } else {
        this.connections = this.connections.filter(c => c !== conn);
      }
    });

    if (isSignaling) {
      // A signaling connection that never opens (peer unreachable, etc.) may
      // emit 'error' instead of 'close' — without this, its stale queue would
      // never be cleared and would get flushed alongside a later, unrelated
      // connection attempt to the same target.
      conn.on('error', () => {
        this.discardSignalingConnection(conn);
      });
    }
  }

  /**
   * Drops a signaling connection and any messages still queued for it —
   * but only if `conn` is still the connection currently registered for its
   * peer. If a newer connection has already replaced it (e.g. a delayed or
   * duplicate 'close'/'error' event arriving for a connection that was
   * already superseded), that newer connection's own queued messages must
   * not be wiped out by this stale event.
   */
  private discardSignalingConnection(conn: DataConnection): void {
    if (this.signalingConnections.get(conn.peer) === conn) {
      this.signalingConnections.delete(conn.peer);
      this.pendingSignalingSends.delete(conn.peer);
    }
  }

  /** Lazily creates (or reuses) the reliable signaling DataConnection to targetId. */
  private getOrCreateSignalingConnection(targetId: string): DataConnection | null {
    const existing = this.signalingConnections.get(targetId);
    if (existing) return existing;
    if (!this.peer) return null;

    const conn = this.peer.connect(targetId, {
      label: SIGNALING_LABEL,
      reliable: true,
    });
    this.handleConnection(conn);
    return conn;
  }

  /** Flushes signaling messages queued while the connection to targetId was still opening. */
  private flushPendingSignaling(targetId: string, conn: DataConnection): void {
    const queued = this.pendingSignalingSends.get(targetId);
    if (!queued) return;
    this.pendingSignalingSends.delete(targetId);
    queued.forEach(m => void conn.send(m));
  }

  /**
   * Sends a WebRTC signaling message over the dedicated reliable channel,
   * bypassing the simulated loss-rate gate entirely — a dropped offer/answer/
   * ICE candidate breaks the handshake outright, unlike lossy sync traffic
   * which tolerates the occasional drop.
   */
  private sendSignaling(targetId: string, msg: SyncMessage): void {
    const conn = this.getOrCreateSignalingConnection(targetId);
    if (!conn) return;
    if (conn.open) {
      void conn.send(msg);
    } else {
      const queue = this.pendingSignalingSends.get(targetId) ?? [];
      queue.push(msg);
      this.pendingSignalingSends.set(targetId, queue);
    }
  }

  public setLossRate(rate: number): void {
    this.lossRate = Math.max(0, Math.min(1, rate));
  }

  /** Current simulated packet-loss rate in [0, 1]. */
  public getLossRate(): number {
    return this.lossRate;
  }

  public send(msg: SyncMessage) {
    this.connections.forEach(conn => {
      if (conn.open && Math.random() >= this.lossRate) {
        void conn.send(msg);
      }
    });
  }

  public sendTo(targetId: string, msg: SyncMessage) {
    msg.targetId = targetId;

    if (msg.type.startsWith('webrtc-')) {
      this.sendSignaling(targetId, msg);
      return;
    }

    const conn = this.connections.find(c => c.peer === targetId);
    if (conn && conn.open && Math.random() >= this.lossRate) {
      void conn.send(msg);
    }
  }

  public broadcast(msg: SyncMessage) {
    this.send(msg);
  }

  public destroy() {
    this.isDestroyed = true;
    this.clearReconnectTimer();
    this.reconnectAttempt = 0;
    this.signalingConnections.forEach(conn => conn.close());
    this.signalingConnections.clear();
    this.pendingSignalingSends.clear();
    this.peer?.destroy();
  }
}
